# (C) Copyright 2019-2020 Nuxeo (http://nuxeo.com/) and others.
#
# Contributors:
#     Kevin Leturc <kleturc@nuxeo.com>
#     Anahide Tchertchian
#
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/nuxeo/nuxeo-explorer-export:{{.VERSION}}"
  artifacts:
    - image: nuxeo-explorer-export
      context: docker/nuxeo-explorer-export-docker
      kaniko:
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
        buildArgs:
          BASE_IMAGE: ${DOCKER_REGISTRY}/nuxeo/nuxeo:${NUXEO_IMAGE_VERSION}
          BUILD_TAG: "{{.BUILD_TAG}}"
          VERSION: "{{.VERSION}}"
          USE_LOCAL_EXPLORER: false
          CONNECT_EXPLORER_CLID: "${CONNECT_EXPLORER_CLID}"
          CONNECT_EXPLORER_URL: "${CONNECT_EXPLORER_URL}"
          NUXEO_EXPLORER_PACKAGE: "${NUXEO_EXPLORER_PACKAGE}"
          CONNECT_EXPORT_CLID: "${CONNECT_EXPORT_CLID}"
          CONNECT_EXPORT_URL: "${CONNECT_EXPORT_URL}"
          EXPORT_PACKAGE_LIST: "${EXPORT_PACKAGE_LIST}"
        # disable cache to retrieve packages again
  cluster:
    namespace: platform
    dockerConfig:
      secretName: jenkins-docker-cfg
